import { SiteConfig, PageSEO, ProductItem, DeliveryZone, PortfolioItem, Testimonial, FAQItem } from './types';
import { beverageImages } from './assets/beverageImages';

export const initialSiteConfig: SiteConfig = {
  companyName: 'Adega Bigode Delivery',
  tagline: 'A NOITE COMEÇA AQUI.',
  description: 'Tudo para sua noite sem sair de casa. Cervejas estalando de geladas, destilados originais, vinhos selecionados, gelo e combos para resenhas entregues em minutos.',
  logoUrl: beverageImages.brandLogo,
  primaryColor: '#090A0C', // Preto profundo
  accentColor: '#E5A93C',  // Dourado âmbar
  email: 'pedidos@bigodedelivery.com.br',
  phone: '+55 (38) 98860-8576',
  whatsapp: '+55 38 98860-8576',
  address: 'Rua da Noite, 420 - Centro / Vila Boêmia',
  instagramUrl: 'https://instagram.com/adegabigode.oficial',
  isOpenNow: true,
  openingHoursText: 'Terça a Domingo das 18h às 04h | Finais de Semana até 05h',
  estimatedDeliveryText: '25 a 35 min',
  minimumOrder: 25.0,
  freeDeliveryThreshold: 110.0,
  announcementTicker: '⚡ ABERTO AGORA • ENTREGANDO EM ATÉ 35 MIN • FRETE GRÁTIS ACIMA DE R$ 110 • BEBIDA TRINCANDO DE GELADA!',
  sectionOrder: ['hero', 'categories', 'combos', 'beers', 'spirits', 'ice_convenience', 'about_adega', 'gallery_night', 'testimonials', 'faq', 'cta_order'],
};

export const initialDeliveryZones: DeliveryZone[] = [
  { id: '1', name: 'Centro / Região Central', fee: 6.00, estimatedMinutes: 20 },
  { id: '2', name: 'Vila Boêmia / Jardins', fee: 7.50, estimatedMinutes: 25 },
  { id: '3', name: 'Bela Vista / Consolação', fee: 8.00, estimatedMinutes: 25 },
  { id: '4', name: 'Pinheiros / Vila Madalena', fee: 9.00, estimatedMinutes: 30 },
  { id: '5', name: 'Moema / Vila Mariana', fee: 10.00, estimatedMinutes: 35 },
  { id: '6', name: 'Santana / Zona Norte', fee: 12.00, estimatedMinutes: 40 },
  { id: '7', name: 'Outros Bairros (Consulte no Whats)', fee: 14.00, estimatedMinutes: 45 },
];

export const initialProducts: ProductItem[] = [
  // --- COMBOS DA NOITE ---
  {
    id: 'combo-1',
    name: 'Combo After Dark: Black Label 1L + 4 Red Bull + Gelo de Coco',
    category: 'combos',
    categoryLabel: 'Combos da Noite',
    volume: 'Kit Completo',
    price: 199.90,
    originalPrice: 235.00,
    temperature: 'trincando',
    isCombo: true,
    comboItems: [
      '1x Whisky Johnnie Walker Black Label 1L (Original com dosador)',
      '4x Energéticos Red Bull Energy Drink 250ml (Gelados)',
      '2x Copos Exclusivos Bigode 500ml',
      '2x Gelo de Coco Especial Saborizado'
    ],
    description: 'O combo supremo para iniciar ou manter a sua noite no ápice. Destilado 100% original com selo IPI e energéticos na temperatura certa.',
    imageUrl: beverageImages.comboBlackRedBull,
    badge: 'Mais Vendido',
    isFeatured: true,
    stock: 28,
  },
  {
    id: 'combo-2',
    name: 'Combo Resenha: 24 Heinekens Long Neck + Gelo 5kg',
    category: 'combos',
    categoryLabel: 'Combos da Noite',
    volume: 'Pack 24un + 5kg',
    price: 169.90,
    originalPrice: 194.00,
    temperature: 'trincando',
    isCombo: true,
    comboItems: [
      '24x Cerveja Heineken Long Neck 330ml (Câmara Fria a -4°C)',
      '1x Saco de Gelo Filtrado em Cubos 5kg',
      '1x Abridor Oficial Bigode'
    ],
    description: 'A salvação do churrasco e do jogo. As 24 cervejas saem direto da câmara fria estalando de gelada na sua mão.',
    imageUrl: beverageImages.comboResenhaHeineken,
    badge: 'Cerveja Trincando',
    isFeatured: true,
    stock: 45,
  },
  {
    id: 'combo-3',
    name: 'Combo Gin Tropical: Tanqueray + 4 Tônicas + Especiarias',
    category: 'combos',
    categoryLabel: 'Combos da Noite',
    volume: 'Kit Drinks',
    price: 154.90,
    originalPrice: 179.00,
    temperature: 'trincando',
    isCombo: true,
    comboItems: [
      '1x Gin Tanqueray London Dry 750ml',
      '4x Água Tônica Antarctica 350ml Geladas',
      '1x Sachê de Especiarias Finas (Zimbro + Pimenta Rosa)',
      '1x Saco Gelo Filtrado 2kg'
    ],
    description: 'Refrescante, aromático e pronto para servir com elegância em qualquer encontro.',
    imageUrl: beverageImages.comboGinTropical,
    badge: 'Favorito Delas',
    isFeatured: true,
    stock: 20,
  },
  {
    id: 'combo-4',
    name: 'Combo Esquenta Universitário: Vodka Smirnoff + 4 Balys',
    category: 'combos',
    categoryLabel: 'Combos da Noite',
    volume: 'Kit Esquenta',
    price: 79.90,
    originalPrice: 94.00,
    temperature: 'trincando',
    isCombo: true,
    comboItems: [
      '1x Vodka Smirnoff Red 998ml',
      '4x Energéticos Baly 2L Sabores (Melancia / Tropical)',
      '4x Copos descartáveis reforçados 500ml'
    ],
    description: 'Excelente custo-benefício para abastecer a galera no esquenta antes da balada sem pesar no bolso.',
    imageUrl: beverageImages.comboEsquentaVodka,
    badge: 'Economia',
    isFeatured: true,
    stock: 35,
  },

  // --- CERVEJAS ---
  {
    id: 'beer-1',
    name: 'Heineken Long Neck 330ml',
    category: 'cervejas',
    categoryLabel: 'Cervejas',
    volume: '330ml',
    price: 8.49,
    originalPrice: 9.50,
    temperature: 'trincando',
    description: 'Puro malte, sabor marcante e refrescância inconfundível. Sai da nossa câmara fria no ponto exato de consumo.',
    imageUrl: beverageImages.beerHeinekenCold,
    badge: '🥶 -4°C Real',
    isFeatured: true,
    stock: 240,
  },
  {
    id: 'beer-2',
    name: 'Corona Extra Long Neck 330ml com Limão',
    category: 'cervejas',
    categoryLabel: 'Cervejas',
    volume: '330ml',
    price: 8.99,
    originalPrice: 10.00,
    temperature: 'trincando',
    description: 'A clássica cerveja mexicana que combina com noites quentes e resenhas descontraídas. Acompanha fatia de limão taiti.',
    imageUrl: beverageImages.beerCoronaCold,
    badge: 'Mais Pedida',
    isFeatured: true,
    stock: 180,
  },
  {
    id: 'beer-3',
    name: 'Stella Artois Long Neck 330ml Gelada',
    category: 'cervejas',
    categoryLabel: 'Cervejas',
    volume: '330ml',
    price: 8.49,
    originalPrice: 9.20,
    temperature: 'trincando',
    description: 'Cerveja belga de tradição centenária com lúpulos nobres Saaz e equilíbrio impecável entre aroma e amargor.',
    imageUrl: beverageImages.beerStellaArtois,
    isFeatured: false,
    stock: 95,
  },
  {
    id: 'beer-4',
    name: 'Spaten Munich Helles Puro Malte 350ml',
    category: 'cervejas',
    categoryLabel: 'Cervejas',
    volume: '350ml',
    price: 5.79,
    originalPrice: 6.50,
    temperature: 'trincando',
    description: 'Cerveja de tradição Munich Helles alemã desde 1397, puro malte, corpo presente e amargor suave.',
    imageUrl: beverageImages.beerSpatenMunich,
    badge: 'Oferta da Rodada',
    isFeatured: true,
    stock: 310,
  },
  {
    id: 'beer-5',
    name: 'Pack Cerveja Amstel Puro Malte 12 Latas 350ml',
    category: 'cervejas',
    categoryLabel: 'Cervejas',
    volume: '12x 350ml',
    price: 49.90,
    originalPrice: 56.90,
    temperature: 'trincando',
    description: 'Pack lacrado conservado na temperatura ideal para encher o cooler da sua festa.',
    imageUrl: beverageImages.beerAmstelPack,
    isFeatured: false,
    stock: 60,
  },
  {
    id: 'beer-6',
    name: 'Budweiser American Lager Long Neck 330ml',
    category: 'cervejas',
    categoryLabel: 'Cervejas',
    volume: '330ml',
    price: 7.99,
    originalPrice: 8.90,
    temperature: 'trincando',
    description: 'Lager clássica americana maturada em madeira de faia para um sabor marcante e final refrescante.',
    imageUrl: beverageImages.beerBudweiserBottle,
    badge: 'Geladíssima',
    isFeatured: true,
    stock: 140,
  },
  {
    id: 'beer-7',
    name: 'Brahma Duplo Malte Lata 350ml Trincando',
    category: 'cervejas',
    categoryLabel: 'Cervejas',
    volume: '350ml',
    price: 5.49,
    originalPrice: 6.20,
    temperature: 'trincando',
    description: 'Combinação perfeita de malte Pilsen com malte tostado. Cerveja cremosa e dourada.',
    imageUrl: beverageImages.beerBrahmaDuplo,
    isFeatured: false,
    stock: 200,
  },

  // --- DESTILADOS ---
  {
    id: 'spirit-1',
    name: 'Whisky Johnnie Walker Black Label 12 Anos 1L',
    category: 'destilados',
    categoryLabel: 'Destilados',
    volume: '1 Litro',
    price: 159.90,
    originalPrice: 179.90,
    temperature: 'ambiente',
    description: 'Blended Scotch Whisky ícone mundial envelhecido por 12 anos, com notas de frutas escuras, baunilha e toque defumado.',
    imageUrl: beverageImages.whiskyBlackLabel,
    badge: 'Autêntico c/ Selo',
    isFeatured: true,
    stock: 42,
  },
  {
    id: 'spirit-2',
    name: 'Whisky Jack Daniel’s Old No. 7 Tennessee 1L',
    category: 'destilados',
    categoryLabel: 'Destilados',
    volume: '1 Litro',
    price: 149.90,
    originalPrice: 165.00,
    temperature: 'ambiente',
    description: 'Tennessee Whiskey filtrado gota a gota em 3 metros de carvão de bordo para suavidade lendária.',
    imageUrl: beverageImages.whiskyJackDaniels,
    isFeatured: true,
    stock: 36,
  },
  {
    id: 'spirit-3',
    name: 'Gin Tanqueray London Dry 750ml',
    category: 'destilados',
    categoryLabel: 'Destilados',
    volume: '750ml',
    price: 119.90,
    originalPrice: 139.90,
    temperature: 'ambiente',
    description: 'Quatro vezes destilado com os botânicos mais refinados: zimbro, coentro, angélica e alcaçuz.',
    imageUrl: beverageImages.ginTanquerayBottle,
    badge: 'Top Drinks',
    isFeatured: true,
    stock: 25,
  },
  {
    id: 'spirit-4',
    name: 'Vodka Absolut Regular Original 1L',
    category: 'destilados',
    categoryLabel: 'Destilados',
    volume: '1 Litro',
    price: 99.90,
    originalPrice: 112.00,
    temperature: 'ambiente',
    description: 'Vodka sueca pura produzida exclusivamente com trigo de inverno e água profunda de Ahus sem adição de açúcar.',
    imageUrl: beverageImages.vodkaAbsolutBottle,
    isFeatured: false,
    stock: 30,
  },
  {
    id: 'spirit-5',
    name: 'Gin Beefeater London Dry 750ml',
    category: 'destilados',
    categoryLabel: 'Destilados',
    volume: '750ml',
    price: 109.90,
    originalPrice: 125.00,
    temperature: 'ambiente',
    description: 'Clássico londrino com 9 botânicos naturais macerados por 24 horas antes da destilação.',
    imageUrl: beverageImages.ginBeefeaterBottle,
    isFeatured: false,
    stock: 20,
  },
  {
    id: 'spirit-6',
    name: 'Whisky Johnnie Walker Red Label 1L',
    category: 'destilados',
    categoryLabel: 'Destilados',
    volume: '1 Litro',
    price: 98.90,
    originalPrice: 115.00,
    temperature: 'ambiente',
    description: 'O whisky escocês pioneiro da Johnnie Walker, vibrante e versátil para coquetéis e drinks.',
    imageUrl: beverageImages.whiskyRedLabel,
    isFeatured: false,
    stock: 35,
  },

  // --- VINHOS & ESPUMANTES ---
  {
    id: 'wine-1',
    name: 'Vinho Chileno Casillero del Diablo Cabernet Sauvignon 750ml',
    category: 'vinhos',
    categoryLabel: 'Vinhos',
    volume: '750ml',
    price: 59.90,
    originalPrice: 69.90,
    temperature: 'ambiente',
    description: 'Notas de cereja preta, ameixa madura e toques elegantes de baunilha e carvalho tostado.',
    imageUrl: beverageImages.wineCabernetBottle,
    badge: 'Seleção da Adega',
    isFeatured: true,
    stock: 22,
  },
  {
    id: 'wine-2',
    name: 'Espumante Chandon Réserve Brut 750ml Gelado',
    category: 'vinhos',
    categoryLabel: 'Vinhos',
    volume: '750ml',
    price: 98.90,
    originalPrice: 115.00,
    temperature: 'trincando',
    description: 'Fresco, frutado e sofisticado com borbulhas finas e perenes. Pronto para brindar na temperatura ideal.',
    imageUrl: beverageImages.wineChandonSparkling,
    badge: 'Brinde VIP',
    isFeatured: false,
    stock: 18,
  },

  // --- GELO, CARVÃO & ESSENCIAIS ---
  {
    id: 'ice-1',
    name: 'Gelo Filtrado em Cubos Saco 5kg',
    category: 'gelo_essenciais',
    categoryLabel: 'Gelo & Essenciais',
    volume: '5kg',
    price: 15.00,
    originalPrice: 18.00,
    temperature: 'trincando',
    description: 'Gelo cristalino, feito com água 100% filtrada. Cubos maciços que demoram mais para derreter no seu cooler.',
    imageUrl: beverageImages.iceBagCubes,
    badge: 'Salva-Vidas',
    isFeatured: true,
    stock: 90,
  },
  {
    id: 'ice-2',
    name: 'Gelo de Coco Natural para Drinks (Pct com 4un)',
    category: 'gelo_essenciais',
    categoryLabel: 'Gelo & Essenciais',
    volume: '4x 200ml',
    price: 14.90,
    originalPrice: 17.00,
    temperature: 'trincando',
    description: 'Gelo saborizado de água de coco natural. Perfeito para acompanhar whisky e drinks sem aguar.',
    imageUrl: beverageImages.iceCocoDrinks,
    isFeatured: false,
    stock: 55,
  },
  {
    id: 'ice-3',
    name: 'Carvão Vegetal Selecionado 3kg Eucalipto',
    category: 'gelo_essenciais',
    categoryLabel: 'Gelo & Essenciais',
    volume: '3kg',
    price: 18.90,
    originalPrice: 22.00,
    temperature: 'ambiente',
    description: 'Brasa rápida e duradoura sem faíscas. A lenha certa para quem não quer perder tempo no churrasco.',
    imageUrl: beverageImages.barbecueCharcoalSack,
    isFeatured: false,
    stock: 40,
  },
  {
    id: 'ice-4',
    name: 'Kit Copos Reforçados 500ml (Pct 25 unidades)',
    category: 'gelo_essenciais',
    categoryLabel: 'Gelo & Essenciais',
    volume: '25un',
    price: 12.90,
    originalPrice: 15.00,
    temperature: 'ambiente',
    description: 'Copos rígidos transparentes para servir chopp, drinks e cerveja com conforto.',
    imageUrl: beverageImages.clearPartyCups,
    isFeatured: false,
    stock: 75,
  },

  // --- SNACKS & SEM ÁLCOOL ---
  {
    id: 'non-alc-1',
    name: 'Red Bull Energy Drink Lata 250ml Gelado',
    category: 'sem_alcool',
    categoryLabel: 'Sem Álcool & Energéticos',
    volume: '250ml',
    price: 10.90,
    originalPrice: 12.00,
    temperature: 'trincando',
    description: 'Te dá asas para manter o ritmo da noite. Servido extremamente gelado.',
    imageUrl: beverageImages.redBullCanChilled,
    badge: 'Mais Vendido',
    isFeatured: true,
    stock: 120,
  },
  {
    id: 'non-alc-2',
    name: 'Energético Monster Energy Green 473ml',
    category: 'sem_alcool',
    categoryLabel: 'Sem Álcool & Energéticos',
    volume: '473ml',
    price: 12.90,
    originalPrice: 14.50,
    temperature: 'trincando',
    description: 'Sabor clássico Monster com taurina, cafeína e vitaminas B para recarregar sua energia.',
    imageUrl: beverageImages.monsterEnergyCan,
    isFeatured: false,
    stock: 80,
  },
  {
    id: 'non-alc-3',
    name: 'Refrigerante Coca-Cola Original Lata 350ml Gelada',
    category: 'sem_alcool',
    categoryLabel: 'Sem Álcool & Energéticos',
    volume: '350ml',
    price: 5.50,
    originalPrice: 6.00,
    temperature: 'trincando',
    description: 'O refrigerante mais famoso do mundo, entregue estupidamente trincando.',
    imageUrl: beverageImages.cocaColaChilled,
    isFeatured: false,
    stock: 150,
  },
  {
    id: 'beer-pack-1',
    name: 'Pack Cerveja Amstel Puro Malte 12 Latas 350ml Geladas',
    category: 'cervejas',
    categoryLabel: 'Cervejas',
    volume: '12x 350ml',
    price: 49.90,
    originalPrice: 56.00,
    temperature: 'trincando',
    description: 'Pack econômico com 12 latas puro malte, entregues no gelo para abastecer a galera.',
    imageUrl: beverageImages.beerAmstelPack,
    badge: 'Pack Galera',
    isFeatured: true,
    stock: 65,
  },
  {
    id: 'conv-3',
    name: 'Kit Copos Balada Cristal 500ml (25 unidades)',
    category: 'gelo_essenciais',
    categoryLabel: 'Gelo, Carvão & Copos',
    volume: '25 unidades',
    price: 14.90,
    originalPrice: 18.00,
    temperature: 'ambiente',
    description: 'Copos cristal resistentes para servir drinks, chopp e cerveja com comodidade.',
    imageUrl: beverageImages.clearPartyCups,
    isFeatured: false,
    stock: 110,
  }
];

export const initialPortfolioItems: PortfolioItem[] = [
  {
    id: 'gal-brand-art',
    title: 'Arte Oficial & Identidade Visual Bigode After Dark',
    category: 'Identidade & Lifestyle',
    description: 'A estética noturna autêntica da Adega Bigode Delivery, unindo o preto profundo com o dourado âmbar característico.',
    imageUrl: beverageImages.brandArtHero,
    isFeatured: true,
  },
  {
    id: 'gal-1',
    title: 'Câmara Fria a -4°C da Adega Bigode',
    category: 'Nossa Estrutura',
    description: 'Aqui a cerveja não dorme em prateleira morna. Sistema de refrigeração industrial contínua para saída imediata estalando.',
    imageUrl: beverageImages.beerColdFreezer,
    isFeatured: true,
  },
  {
    id: 'gal-2',
    title: 'Fachada Noturna da Adega Bigode',
    category: 'Adega Bigode Oficial',
    description: 'Loja física e ponto de distribuição oficial da Adega Bigode aberta até as 04h da madrugada para atendimento de balcão e entrega rápida com câmara fria a -4°C.',
    imageUrl: beverageImages.adegaFrontNight,
    isFeatured: true,
  },
  {
    id: 'gal-3',
    title: 'Logística Noturna Rápida e Discreta',
    category: 'Operação',
    description: 'Motoboys preparados para entregar suas bebidas com segurança, agilidade e discrição em qualquer horário.',
    imageUrl: beverageImages.deliveryMotoboyNight,
    isFeatured: true,
  },
  {
    id: 'gal-4',
    title: 'Comemoração em Frente à Adega Bigode',
    category: 'Lifestyle Adega Bigode',
    description: 'Amigos reunidos em pé em frente à Adega Bigode, confraternizando e brindando com Red Label e copos de whisky na noite.',
    imageUrl: beverageImages.beerCheersNight,
    isFeatured: true,
  }
];

export const initialTestimonials: Testimonial[] = [
  {
    id: 'dep-1',
    name: 'Matheus Albuquerque',
    neighborhood: 'Vila Boêmia',
    comment: 'Sexta-feira meia-noite a cerveja acabou no meio do churrasco. Pedi o Combo Resenha com 24 Heinekens pelo site e em 22 minutos o motoboy tava tocando o interfone. As garrafas tavam saindo gelo. Sensacional!',
    rating: 5,
    favoriteItem: 'Combo Resenha 24 Heinekens',
    deliveryTime: '22 minutos',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    date: 'Há 3 dias',
    isFeatured: true,
  },
  {
    id: 'dep-2',
    name: 'Camila Vasconcelos',
    neighborhood: 'Centro',
    comment: 'O Combo Gin Tanqueray com as tônicas geladas e o sachê de especiarias salvou nosso encontro. Preço muito mais honesto que pedir em app genérico e sem surpresa de taxa absurda. Virei cliente fiel.',
    rating: 5,
    favoriteItem: 'Combo Gin Tropical',
    deliveryTime: '28 minutos',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=256&q=80',
    date: 'Ontem à noite',
    isFeatured: true,
  },
  {
    id: 'dep-3',
    name: 'Rodrigo Mendonça',
    neighborhood: 'Pinheiros',
    comment: 'O que mais me impressionou foi a integridade do gelo e da bebida. Chegou trincando mesmo, sem enrolação. Paguei no Pix rápido pelo celular e recebi o comprovante e aviso no WhatsApp em tempo real.',
    rating: 5,
    favoriteItem: 'Combo After Dark Black Label',
    deliveryTime: '26 minutos',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
    date: 'Fim de semana passado',
    isFeatured: true,
  }
];

export const initialFAQs: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'A cerveja realmente chega gelada para consumo imediato?',
    answer: 'Sim! Nosso maior compromisso é que você não precise esperar nem 1 minuto para abrir a bebida. Temos câmara fria industrial regulada a -4°C e nossos entregadores usam caixas térmicas vedadas. A garrafa sai estalando na sua mão.',
    category: 'Qualidade & Entrega',
    order: 1,
  },
  {
    id: 'faq-2',
    question: 'Quais são os horários de entrega na madrugada?',
    answer: 'Funcionamos de Terça a Domingo das 18h às 04h da manhã. Nas noites de Sexta e Sábado, estendemos o atendimento até as 05h da madrugada para garantir que nenhuma resenha fique desabastecida.',
    category: 'Horários & Funcionamento',
    order: 2,
  },
  {
    id: 'faq-3',
    question: 'Quais formas de pagamento são aceitas?',
    answer: 'Aceitamos Pix (com geração automática de QR Code e chave Copia e Cola), Cartão de Crédito e Débito (na maquininha com o entregador ou online) e Dinheiro em espécie (basta sinalizar se precisa de troco no fechamento).',
    category: 'Pagamentos',
    order: 3,
  },
  {
    id: 'faq-4',
    question: 'Existe valor de pedido mínimo e frete grátis?',
    answer: 'O pedido mínimo para entrega é de apenas R$ 25,00. E para pedidos a partir de R$ 110,00, a entrega é 100% gratuita dentro do raio padrão de atendimento!',
    category: 'Taxas & Pedido Mínimo',
    order: 4,
  },
  {
    id: 'faq-5',
    question: 'Os destilados são originais e possuem selo de procedência?',
    answer: 'Absolutamente. Todas as nossas garrafas são adquiridas diretamente de distribuidores homologados pelas marcas oficiais, acompanhadas de nota fiscal e selo IPI intacto. Jamais comercializamos produtos de procedência duvidosa.',
    category: 'Produtos & Autenticidade',
    order: 5,
  },
  {
    id: 'faq-6',
    question: 'Como faço para acompanhar o status da minha entrega?',
    answer: 'Assim que você finaliza o pedido pelo site, você recebe o código de acompanhamento em tempo real (Recebido ➔ Na Câmara Fria ➔ Em Rota com Motoboy ➔ Chegando) e pode conversar instantaneamente pelo WhatsApp com nosso atendente.',
    category: 'Rastreamento',
    order: 6,
  }
];

export const initialSEOList: PageSEO[] = [
  {
    pageId: 'home',
    pageName: 'Início',
    metaTitle: 'Bigode Delivery | Adega After Dark & Bebidas Geladas 24h',
    metaDescription: 'Cervejas estalando de geladas, destilados originais, vinhos, gelo e combos noturnos entregues na sua porta em até 35 min. A noite começa aqui!',
    keywords: 'adega delivery, bebida gelada entrega, bigode delivery, adega aberta madrugada, comprar cerveja online, combo de whisky, gelo 5kg entrega',
    ogImage: beverageImages.heroAdegaBanner,
  },
  {
    pageId: 'catalog',
    pageName: 'Cardápio & Catálogo',
    metaTitle: 'Cardápio de Bebidas & Combos | Bigode Delivery',
    metaDescription: 'Confira nosso catálogo completo de cervejas puro malte, destilados, combos promocionais, gelo e petiscos prontos para entrega.',
    keywords: 'cardapio adega, preco de cerveja delivery, combos de bebida, comprar gin delivery',
  },
  {
    pageId: 'about',
    pageName: 'A Adega Bigode',
    metaTitle: 'Sobre a Adega Bigode | Conheça Nossa História & Estrutura',
    metaDescription: 'Mais que um delivery de bebidas: nossa câmara fria, história e dedicação para transformar a noite da nossa cidade.',
    keywords: 'historia adega bigode, adega fisica, câmara fria cerveja',
  },
  {
    pageId: 'track',
    pageName: 'Acompanhar Pedido',
    metaTitle: 'Rastrear Meu Pedido | Bigode Delivery',
    metaDescription: 'Acompanhe seu pedido em tempo real desde a separação no freezer até a rota do motoboy.',
    keywords: 'rastreio pedido adega, status da entrega bigode',
  },
  {
    pageId: 'faq',
    pageName: 'Dúvidas Frequentes',
    metaTitle: 'FAQ & Atendimento | Bigode Delivery',
    metaDescription: 'Tire suas dúvidas sobre tempo de entrega, bairros atendidos, formas de pagamento e temperatura das bebidas.',
    keywords: 'faq bigode delivery, duvidas entrega de bebida',
  },
  {
    pageId: 'contact',
    pageName: 'Contato & WhatsApp',
    metaTitle: 'Fale Conosco & WhatsApp Oficial | Bigode Delivery',
    metaDescription: 'Fale diretamente com nossa equipe da adega ou acione o suporte de entregas no WhatsApp.',
    keywords: 'whatsapp adega bigode, telefone delivery bebidas',
  }
];
